# Generated by Django 3.2.6 on 2021-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0015_auto_20210809_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
