# Generated by Django 3.2.6 on 2021-08-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0016_patientinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
