# Generated by Django 3.2.6 on 2021-08-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0020_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='designation',
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
