# Generated by Django 3.2.6 on 2021-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0022_doctorinfo_hospitalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True),
        ),
    ]
