# Generated by Django 3.2.6 on 2021-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0024_auto_20210812_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='bloodPressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
