# Generated by Django 3.2.6 on 2021-08-12 17:41

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0025_auto_20210812_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='bloodPressure',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
